name: Deploy
on:
 push:
  branches: [main]

jobs:
  Deploy:

   name: "deploy to Nginx_Server"
   runs-on: ubuntu-latest
   
   steps:
     - uses: actions/checkout@v2
     - name: install nginx into Nginx_server and deploy file    
       env:
        PRIVATE_KEY: ${ { secret.PRIVATE_SECRET_KEY } }
       run: |
        echo "$PRIVATE_KEY" > NewAxeCred-3.pem && chmod 600 NewAxeCred-3.pem

        echo "copying local file into Nginx_server"
        scp -o StrictHostKeyChecking=no -i NewAxeCred-3.pem index.html ec2-user@ec2-18-175-134-165.eu-west-2.compute.amazonaws.com:~/

        echo "connecting to Nginx_server via ssh & installing nginx"
        ssh -o StrictHostKeyChecking=no -i NewAxeCred-3.pem ec2-user@ec2-18-175-134-165.eu-west-2.compute.amazonaws.com '
        sudo yum install nginx -y
        sudo service ngix start
        sudo mv ~/index.html /usr/share/nginx/html
        '



